codename: 王王
helloservice: hi
spring: 
  http: 
    encoding: 
      charset: UTF-8 
      enabled: true 
      force: true 
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    #driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.182.150
    port: 8539
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 20
        max-wait: 3000
        max-idle: 10
        min-idle: 2
mybatis:
  #mapper-locations: classpath:mappers/*.xml
  type-aliases-package: SpringBootDemo.Entities
zipkin:
  serviceName: zipkin-demo
  url: http://ui.zipkin.com
  connectTimeout: 6000
  readTimeout: 6000
  flushInterval: 1
  compressionEnabled: true
server: 
  #servlet:
  #  context-path: /zipkinTest
  tomcat: 
    uri-encoding: UTF-8
logging:
  level:
     SpringBootDemo.Dao: debug